//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentsG : DbContext
    {
        public StudentsG()
            : base("name=Students")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FACULTET> FACULTETs { get; set; }
        public virtual DbSet<KOLICHESTVO_CHASOV> KOLICHESTVO_CHASOV { get; set; }
        public virtual DbSet<KUR> KURS { get; set; }
        public virtual DbSet<OCENKA> OCENKAs { get; set; }
        public virtual DbSet<PREDMET> PREDMETs { get; set; }
        public virtual DbSet<SPECIALNOST> SPECIALNOSTs { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TEACHER> TEACHERs { get; set; }
    }
}
