//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class KOLICHESTVO_CHASOV
    {
        public int ID_STUDENT { get; set; }
        public string IMYA { get; set; }
        public string FAMILIYA { get; set; }
        public Nullable<int> ID_PREDMET { get; set; }
        public Nullable<int> KOLVO_CHASOV { get; set; }
    
        public virtual PREDMET PREDMET { get; set; }
        public virtual Student Student { get; set; }
    }
}
