//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class KUR
    {
        public int ID_STUDENT { get; set; }
        public int ID_FACULTET { get; set; }
        public Nullable<int> KURS { get; set; }
    
        public virtual FACULTET FACULTET { get; set; }
        public virtual Student Student { get; set; }
    }
}
