//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCENKA
    {
        public int ID_STUDENT { get; set; }
        public int ID_PREDMET { get; set; }
        public int NOM_ZACHETKI { get; set; }
        public string VID_OTCHET { get; set; }
        public string OCENKA1 { get; set; }
        public System.DateTime DATA_SDACHI { get; set; }
    
        public virtual PREDMET PREDMET { get; set; }
        public virtual Student Student { get; set; }
    }
}
