//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PREDMET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PREDMET()
        {
            this.KOLICHESTVO_CHASOV = new HashSet<KOLICHESTVO_CHASOV>();
            this.OCENKAs = new HashSet<OCENKA>();
        }
    
        public int ID_PREDMET { get; set; }
        public string NAME_PREDMET { get; set; }
        public int ID_TEACHER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KOLICHESTVO_CHASOV> KOLICHESTVO_CHASOV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OCENKA> OCENKAs { get; set; }
        public virtual TEACHER TEACHER { get; set; }
    }
}
