//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEACHER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEACHER()
        {
            this.PREDMETs = new HashSet<PREDMET>();
        }
    
        public int ID_TEACHER { get; set; }
        public string FAMILIYA { get; set; }
        public string IMYA { get; set; }
        public string OTCHESTVO { get; set; }
        public Nullable<System.DateTime> TRUOUSTROISTVO { get; set; }
        public Nullable<int> GOD_STAZH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PREDMET> PREDMETs { get; set; }
    }
}
